### ISSUE TITLE
Final screen issues

### ISSUE THREAD

**Issue by DerekMoss95** [WorldsEndless/retabled#2]
I am pretty sure I have found the reason why it doesn't return the correct final screen number from retabled. On line 199 of core.cljc, it decrements the amount of partitions. So this might be an in-congruence between making 1 the base amount and it being 0 elsewhere. I am not totally sure but I think the problem is line 199. When it is fed six entries, it says the final page is 0 when it should be 1. 

`max-screens (dec (count parted-entries))]`

**Comment by DerekMoss95** [comment]
I verified that the issue is with re-frame. I added four more jobs so that there would be 10 entries and there is now two pages and the buttons work. If there is 9 or less, it doesn't set final-screen to 1. It needs two full pages in order to work. It definitely is an issue with re-frame and not an issue with what parameters are given to the retabled call.

**Comment by WorldsEndless** [comment]
Fixed in next version, using a pad with partition
