### ISSUE TITLE
Fix the colspan attribute for the table header (Paging buttons row)

### ISSUE THREAD

**Issue by DerekMoss95** [WorldsEndless/retabled#4]
Like the title says, retabled needs the colspan attribute on line 123 to be fixed. 

`[:td.cell.screen-controls` {:colSpan "0"}) `

The 0 should actually be 100%

**Comment by WorldsEndless** [comment]
Because reports that full colSpan could be achieved with CSS are erroneous, the proper colspan is now dynamically calculated from the number of entries provided.
